---
# TODO: Set up Travis CI release.
language: go
go: 1.10.x
sudo: false
env:
  - DEP_VERSION="0.4.1"
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get github.com/mitchellh/gox
install: dep ensure
script:
  - make
  - make test
  - make build
